/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tenaciouspanda.jobstretch.frontend;

import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 *
 * @author Simon
 */
public class JobStretchFrame extends javax.swing.JFrame {

    private JComponent curPanel = null;

    /**
     * Creates new form JobStretchFrame
     */
    public JobStretchFrame() {
        initComponents();
    }
    
    public void setPanel(JPanel panel){
        if(curPanel != null)
            this.remove(curPanel);
        curPanel = panel;
        this.getContentPane().add(curPanel);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
